baseURL : https://wegoatdev.netlify.app/
languageCode : en
title : We Goat Dev

params:
    description: Explore dev problem through code

staticDir: static

permalinks:
  posts : /:title/

summaryLength: 25

paginate : 12